server:
  port: 8888
spring:
  application:
    name: ai-mcp-client
  main:
    banner-mode: off # 关闭启动时的spring 控制台输出的banner图标
    #web-application-type: none

  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: aaa
      # spring-ai-autoconfigure-model-openai-1.0.0-M7-sources.jar!\org\springframework\ai\model\openai\autoconfigure\OpenAiConnectionProperties.java
      # 里会设置默认值：https://api.openai.com
      # 但是openai限制国内访问，改用兼容openai的deepseek，注意要配置下面的model，否则会抛异常：Model not exist.
      # 注：deepseek也使用 spring-ai-starter-model-openai
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        name: beinet-ai-mcp-client
        request-timeout: 600s
        # stdio模式的MCP Server配置
#        stdio:
#          servers-configuration: file:D:/mine/study/aidemo/mcp_server_config.json
        # sse模式的MCP Server配置
        sse:
          connections:
            weather-mcp-server:
              url: http://127.0.0.1:8080

logging:
  level:
    # io.modelcontextprotocol.client.McpAsyncClient: debug
    org.springframework.ai.chat.client.advisor: DEBUG