server:
  port: 8080
spring:
  application:
    name: beinet-admin
  profiles:
    active: local
  cloud:
    config:
      profile: ${spring.profiles.active}
      label: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.72.155:3306/dev?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&socketTimeout=600000&connectTimeout=15000&rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=round&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: 10.100.72.155
      port: 8379
      password: beinet123456
      database: 15            # 数据库索引，注意 0到15

sdk:
  app-key: sdk
  secure-key: cnbeinet.secure
  # todo: ak/sk可以访问的api列表
  api:
    - /version